version: 2.1
jobs:
  server_heroku_push:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false
              
      - run:
          name: "Heroku Install"
          command: |
              if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
              else
              echo "Heroku already exists!"
              fi
  
      - run:
          name: Login into Heroku Docker Repository
          command: |
              docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

      - run:
          name: Deploy Heroku Docker Container
          command: |
              heroku container:push web -a quickai
              heroku container:release web -a quickai

workflows:
  version: 2
  deploy_server:
    jobs:
      - server_heroku_push:
          context:
            - aws
          filters:
            branches:
              only:
                - dev
                - master