version: 2
jobs:
  server_heroku_push:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
        - checkout

        - setup_remote_docker:
            docker_layer_caching: false     

        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt

        - run:
            name: run tests
            command: |
                . venv/bin/activate
                cd src
                python3 manage.py migrate
                python3 manage.py test
                
        - run:
            name: "Heroku Install"
            command: |
                if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
                else
                echo "Heroku already exists!"
                fi
    
        - run:
            name: Login into Heroku Docker Repository
            command: |
                docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
                
        - deploy:
          name: "Deploy Container to Heroku"
          command: "bash scripts/deploy-server.sh"

workflows:
  version: 2
  deploy_server:
    jobs:
      - server_heroku_push:
          context:
            - aws
          filters:
            branches:
              only:
                - dev
                - master